name: Build_Kernel_MIUI12_Docker
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04 # Đã cập nhật lên bản mới nhất
    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4
        with:
          repository: MiCode/Xiaomi_Kernel_OpenSource
          ref: angelica-q-oss

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential bison flex libssl-dev libncurses5-dev
          # Cài thêm thư viện để chạy được toolchain 32-bit cũ trên Ubuntu mới
          sudo apt-get install -y lib32z1 lib32ncurses6 lib32stdc++6

      - name: Setup Toolchain (GCC 4.9)
        run: |
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b ndk-release-r21 --depth=1 gcc64
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 -b ndk-release-r21 --depth=1 gcc32
          echo "$(pwd)/gcc64/bin" >> $GITHUB_PATH
          echo "$(pwd)/gcc32/bin" >> $GITHUB_PATH

      - name: Mod Config for Docker
        run: |
          CONF=arch/arm64/configs/angelica_defconfig
          echo "CONFIG_NAMESPACES=y" >> $CONF
          echo "CONFIG_NET_NS=y" >> $CONF
          echo "CONFIG_PID_NS=y" >> $CONF
          echo "CONFIG_IPC_NS=y" >> $CONF
          echo "CONFIG_UTS_NS=y" >> $CONF
          echo "CONFIG_CGROUPS=y" >> $CONF
          echo "CONFIG_CGROUP_CPUACCT=y" >> $CONF
          echo "CONFIG_CGROUP_DEVICE=y" >> $CONF
          echo "CONFIG_CGROUP_FREEZER=y" >> $CONF
          echo "CONFIG_CGROUP_SCHED=y" >> $CONF
          echo "CONFIG_CPUSETS=y" >> $CONF
          echo "CONFIG_BRIDGE=y" >> $CONF
          echo "CONFIG_VETH=y" >> $CONF
          echo "CONFIG_IKCONFIG=y" >> $CONF
          echo "CONFIG_IKCONFIG_PROC=y" >> $CONF

      - name: Build Kernel
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-android-
          export CROSS_COMPILE_ARM32=arm-linux-androideabi-
          
          make O=out angelica_defconfig
          make -j$(nproc --all) O=out Image.gz

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Kernel_MIUI12_Docker_U22
          path: out/arch/arm64/boot/Image.gz
